use Papyrus

--GO
--CREATE PROCEDURE find_NOM (@num_four INT)
--AS
--BEGIN TRANSACTION name

--SELECT * FROM [dbo].[FOURNIS] WHERE @num_four = NUMFOU

--COMMIT TRANSACTION 
--GO;


--GO 
--CREATE PROCEDURE select_comm (@fourni_nom VARCHAR(30))
--AS
--BEGIN TRANSACTION comm
--SELECT ENTCOM.NUMCOM, ENTCOM.DATECOM, ENTCOM.OBSCOM 
--FROM ENTCOM 
--INNER JOIN FOURNIS
--	ON ENTCOM.NUMFOU = FOURNIS.NUMFOU
--WHERE FOURNIS.NOMFOU LIKE @fourni_nom
--COMMIT TRANSACTION
--GO;

--EXEC select_comm 'ECLIPSE';

GO
CREATE PROCEDURE add_fourni(@num INT, @name VARCHAR(30), @street VARCHAR(40), @CP VARCHAR(5), @city VARCHAR(30), @cont VARCHAR(15), @satis INT)
AS 
BEGIN TRANSACTION adder
INSERT INTO FOURNIS 
(NUMFOU, NOMFOU, RUEFOU, POSFOU, VILFOU, CONFOU, SATISF)
VALUES 
(@num ,@name, @street, @CP, @city, @cont, @satis)
COMMIT TRANSACTION 
GO;

GO 
CREATE PROCEDURE del_fourni (@num INT)
AS 
BEGIN TRANSACTION deleter
DELETE FOURNIS WHERE NUMFOU LIKE @num
COMMIT TRANSACTION
GO;

EXEC add_fourni 125, 'MERLIER', 'rue', '92000', 'MULHOUSE', 'antoine', 5;

DELETE FOURNIS WHERE NOMFOU LIKE 'M'; 

SELECT * FROM FOURNIS;

SELECT * FROM ENTCOM;

SELECT FOURNIS.NUMFOU 
FROM FOURNIS 
INNER JOIN ENTCOM 
ON ENTCOM.NUMFOU = FOURNIS.NUMFOU 
WHERE OBSCOM NOT LIKE '';